routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ {
    AdminLoginController,
    LoginController,
    RegisterController
};

use App\Http\Controllers\Admin\ {
    AdminsController,
    AnswersController as AdminAnswersController,
    CategoriesController as AdminCategoriesController,
    HomeController as AdminHomeController,
    QuestionsController as AdminQuestionsController,
    ReportsController as AdminReportsController,
    SettingsController as AdminSettingsController,
    UsersController as AdminUsersController,
};

use App\Http\Controllers\User\ {
    AnswersController,
    CategoriesController,
    CommentsController,
    HomeController,
    NotificationsController,
    ProfileController,
    QuestionsController,
    ReportsController,
    SettingsController,
    SidebarController,
    TagsController,
    WizardController
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Auth Routes */
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->middleware('status.check');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);

});

/* Admin Routes */
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::group(['prefix' => 'admin'], function () {

        Route::get('/login', [AdminLoginController::class, 'login'])->name('admin.login');
        Route::post('/login', [AdminLoginController::class, 'loginAdmin'])->name('admin.loginAdmin');
        Route::post('/logout', [AdminLoginController::class, 'logout'])->name('admin.logout');

        Route::get('register', [AdminHomeController::class, 'create'])->name('admin.register');
        Route::post('register', [AdminHomeController::class, 'store'])->name('admin.register.store');
        Route::get('/', [AdminHomeController::class, 'index'])->name('admin.home');
        Route::resource('/answers', AdminAnswersController::class);
        Route::resource('/admins', AdminsController::class);
        Route::resource('/users', AdminUsersController::class);
        Route::resource('/categories', AdminCategoriesController::class);
        Route::resource('/questions', AdminQuestionsController::class);
        Route::get('/search', [AdminHomeController::class, 'search'])->name('admin.search');

        Route::get('/settings', [AdminSettingsController::class, 'index'])->name('admin.settings');
        Route::put('/settings/update', [AdminSettingsController::class, 'update'])->name('admin.settings.update');

        Route::get('/reports', [AdminReportsController::class, 'index'])->name('reports.index');
        Route::get('/reports/{id}', [AdminReportsController::class, 'show'])->name('reports.show');
        Route::get('/reports/{id}/edit', [AdminReportsController::class, 'edit'])->name('reports.edit');
        Route::get('/reports/{id}/delete/{user?}', [AdminReportsController::class, 'delete'])->name('reports.delete');
        Route::delete('/reports/{id}/deleteReport', [AdminReportsController::class, 'deleteReport'])
            ->name('reports.deleteReport');

    });
});

/* User Routes */
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home');

    /* Question */
    Route::get('/questions/show/{id}/{title?}', [QuestionsController::class, 'show'])->name('question.show');
    Route::get('/ask', [QuestionsController::class, 'create'])->name('user.questions.create');
    Route::post('/questions/store', [QuestionsController::class, 'store'])->name('user.questions.store');
    Route::get('/questions/{id}/edit', [QuestionsController::class, 'edit'])->name('user.questions.edit');
    Route::put('/questions/{id}/update', [QuestionsController::class, 'update'])->name('user.questions.update');
    Route::delete('/questions/{id}', [QuestionsController::class, 'destroy'])->name('user.questions.destroy');

    /* Questions */
    Route::get('/questions', [QuestionsController::class, 'latest'])->name('questions');

    /* All Newest */
    Route::get('/questions/newest', [HomeController::class, 'newest'])->name('questions.newest');
    Route::get('/questions/newest/data', [HomeController::class, 'newestData'])->name('questions.newest.data');

    /* By Interests */
    Route::get('/questions/interested', [HomeController::class, 'interested'])->name('questions.interested');
    Route::get('/questions/interested/data', [HomeController::class, 'interestedData'])
        ->name('questions.interested.data');

    /* Category */
    Route::get('/categories', [CategoriesController::class, 'index'])->name('categories');
    Route::get('/questions/{slug}', [CategoriesController::class, 'questions'])->name('questions.category');
    Route::get('/questions/category/data', [CategoriesController::class, 'questionsData'])
        ->name('questions.category.data');

    /* Tags */
    Route::get('/tags', [TagsController::class, 'index'])->name('tags');
    Route::get('/tags/{name}', [TagsController::class, 'questions'])->name('questions.tag');
    Route::get('/tags/category/data', [TagsController::class, 'questionsData'])->name('questions.tag.data');

    /* Answers */
    Route::post('/answers/store', [AnswersController::class, 'store'])->name('answers.store');
    Route::post('/answers/best', [AnswersController::class, 'best'])->name('answers.best');
    Route::post('/makeVote', [AnswersController::class, 'makeVote'])->name('makeVote');
    Route::post('/loadVotes', [AnswersController::class, 'loadVotes'])->name('loadVotes');
    Route::put('/answers/{id}/update', [AnswersController::class, 'update'])->name('user.answers.update');
    Route::delete('/answers/{id}', [AnswersController::class, 'destroy'])->name('user.answers.destroy');

    /* Comments */
    Route::post('/comments/store', [CommentsController::class, 'store'])->name('user.comments.store');
    Route::put('/comments/{id}/update', [CommentsController::class, 'update'])->name('user.comments.update');
    Route::delete('/comments/{id}', [CommentsController::class, 'destroy'])->name('user.comments.destroy');

    /* Settings */
    Route::get('/settings', [SettingsController::class, 'general'])->name('settings.general');
    Route::put('/settings/general/update', [SettingsController::class, 'update_general'])
        ->name('settings.general.update');
    Route::get('/settings/changepass', [SettingsController::class, 'changepass'])->name('settings.changepass');
    Route::put('/settings/changepass/update', [SettingsController::class, 'update_password'])
        ->name('settings.password.update');
    Route::get('/settings/profile', [SettingsController::class, 'profile'])->name('settings.profile');
    Route::put('/settings/profile/update', [SettingsController::class, 'update_profile'])
        ->name('settings.profile.update');
    Route::get('/settings/myquestions', [SettingsController::class, 'myquestions'])->name('settings.myquestions');

    /* Wizard */
    Route::get('/wizard/step1', [WizardController::class, 'step1'])->name('wizard.step1');
    Route::get('/wizard/step2', [WizardController::class, 'step2'])->name('wizard.step2');
    Route::get('/wizard/step3', [WizardController::class, 'step3'])->name('wizard.step3');
    Route::post('/wizard/step1/store', [WizardController::class, 'step1_store'])->name('wizard.step1.store');
    Route::post('/wizard/step2/store', [WizardController::class, 'step2_store'])->name('wizard.step2.store');
    Route::post('/wizard/step3/store', [WizardController::class, 'step3_store'])->name('wizard.step3.store');


    /* Profile */
    Route::get('/profile/{user_id}', [ProfileController::class, 'index'])->name('profile');
    Route::post('/profile/uploadPicture', [ProfileController::class, 'uploadPicture'])->name('profile.picture');
    Route::post('/profile/uploadCover', [ProfileController::class, 'uploadCover'])->name('profile.cover');

    /* Notifications */
    Route::get('/notifications/get', [NotificationsController::class, 'get'])->name('notifications.get');
    Route::post('/notifications/read', [NotificationsController::class, 'read'])->name('notifications.read');

    /* Sidebar */
    Route::get('/sidebar/topusers', [SidebarController::class, 'topUsers'])->name('sidebar.topusers');

    /* Search */
    Route::get('/search', [HomeController::class, 'search'])->name('user.search');

    /* Report */
    Route::post('/report/question', [ReportsController::class, 'reportQuestion'])->name('report.question');

    Route::get('/splash', [HomeController::class, 'splash'])->name('home.splash');

});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Question extends Model
{

    protected $fillable = [
        'user_id', 'category_id', 'title', 'content'
    ];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function answers()
    {
        return $this->hasMany('App\Models\Answer');
    }

    public function notifications()
    {
        return $this->hasMany('App\Notification');
    }

    public function votes()
    {
        return $this->hasMany('App\Models\Vote');
    }

    public function tags()
    {
        return $this->hasMany('App\Models\Tag');
    }

    public function reports()
    {
        return $this->hasMany('App\Models\Report');
    }

    public  function tags_string()
    {
        $i = count($this->tags);
        $tags_string = '';
        foreach ($this->tags as $tag) {
            $tags_string .= $tag->name;
            if ($last_iteration = (--$i))
                $tags_string .= ', ';
        }
        return $tags_string;
    }

    public function getVotesSumAttribute()
    {
        $sum = 0;
        foreach ($this->votes as $vote) {
            $sum += ($vote->type == 'up' ? 1 : -1);
        }
        return $sum;
    }

    public function hasBestAnswer()
    {
        foreach ($this->answers as $answer) {
            if ($answer->best)
                return true;
        }
        return false;
    }

    public function hasTags()
    {
        return sizeof($this->tags) > 0;
    }

    public function getUrlAttribute()
    {
        return route('question.show', [$this->id, str_replace(' ', '-', $this->title)]);
    }

    public function getSummaryAttribute()
    {
        return mb_substr(strip_tags($this->content), 0, 80) . ' ...';
    }

    public function voteType()
    {
        $vote = Vote::where('user_id', Auth::user()->id)
            ->where('question_id', $this->id)
            ->get()->shift();
        if ($vote != null)
            return $vote->type;
        else
            return null;
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('admin.users.show', compact('user'));
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.users.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {

        $rules = [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|unique:users,email,' . $id,
            'password' => 'nullable|min:8'
        ];

        $attributes = [
            'first_name' => __('admin.first_name'),
            'last_name' => __('admin.last_name'),
            'email' => __('admin.email'),
            'password' => __('admin.password'),
        ];

        $this->validate($request, $rules, [], $attributes);

        $user = User::findOrFail($id);
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->email = $request->email;
        $user->status = $request->status ? 1 : 0;

        if ($request->password != '') {
            $user->password = Hash::make($request->password);
        }

        $user->save();

        return redirect()->route('users.index')->with('success', __('lang.success'));
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index')->with('success', __('lang.success'));
    }
}

app/Http/Controllers/User/AnswersController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Answer;
use App\Helpers\Settings;
use App\Http\Controllers\Controller;
use App\Notification;
use App\Models\Point;
use App\Models\Question;
use App\Models\Vote;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AnswersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['loadVotes', 'voteExists']);
    }

    public function store(Request $request)
    {

        $question = Question::find($request->question_id);

        $answer = new Answer();
        $answer->user_id = Auth::user()->id;
        $answer->question_id = $request->question_id;
        $answer->content = $request->answer_content;

        if ($answer->save() && $answer->user->id != $question->user->id) {
            $notification = new Notification();
            $notification->user_id = $answer->question->user->id;
            $notification->nuser_id = $answer->user_id;
            $notification->type = 'answer';
            $notification->question_id = $answer->question->id;
            $notification->save();
        }

        return redirect()->back();
    }

    public function update(Request $request, $id)
    {

        $answer = Answer::findOrFail($id);
        $answer->content = $request->answer_content;
        $answer->save();

        return redirect()->back();
    }


    public function best(Request $request)
    {
        $question = Question::find($request->question_id);
        $answer = Answer::find($request->answer_id);
        $answer->best = !$answer->best;
        $answer->save();

        $point = new Point();
        $point->user_id = $answer->user->id;
        $point->value = $answer->best ? Settings::get('best_answer_points') : -Settings::get('best_answer_points');
        $point->save();

        foreach ($question->answers as $answer) {
            if ($answer->id != $request->answer_id && $answer->best) {

                $answer->best = false;
                $answer->save();

                $point = new Point();
                $point->user_id = $answer->user->id;
                $point->value =  -Settings::get('best_answer_points');
                $point->save();
            }
        }

        if ($answer->save() && $answer->best && $answer->user->id != $question->user->id) {
            $notification = new Notification();
            $notification->user_id = $answer->user_id;
            $notification->nuser_id = $question->user_id;
            $notification->type = 'best';
            $notification->question_id = $question->id;
            $notification->save();
        }

        return redirect()->back();
    }

    public function makeVote(Request $request)
    {
        if (Auth::user()) {

            $count = null;

            if ($request->answer_id != null && $request->question_id == null) {
                $user_id = Answer::find($request->answer_id)->user->id;
                if (Auth::user()->id != $user_id) {
                    Vote::makeVote(Auth::user()->id, 'answer', $request->answer_id, $request->type);
                    $count = Answer::find($request->answer_id)->votesSum;
                }
            } elseif ($request->question_id != null && $request->answer_id == null) {
                $user_id = Question::find($request->question_id)->user->id;
                if (Auth::user()->id != $user_id) {
                    Vote::makeVote(Auth::user()->id, 'question', $request->question_id, $request->type);
                    $count = Question::find($request->question_id)->votesSum;
                }
            }

            return $count;
        }
    }

    public function destroy($id)
    {
        $answer = Answer::findOrFail($id);
        $answer->delete();

        return redirect()->back();
    }
}

resources/views/user/components/footer.blade.php
<div class="footer">
    <div class="row">
        <div class="footer-container">
            <div class="nav">
                <a class="nav-link" href="">{{ __('lang.terms') }}</a>
                <a class="nav-link" href="">{{ __('lang.privacy_policy') }}</a>
                <a class="nav-link" href="">{{ __('lang.about') }}</a>
            </div>
            <div class="copyright">
                {{ __('lang.copyright') }}
            </div>
        </div>
    </div>
</div>

resources/views/user/components/header.blade.php
<div class="navbar">
    <div class="row">
        <div class="navbar-container">
            <div class="navbar-header">
                <div class="nav-btn toggle-search mobile">
                    <i data-feather="search"></i>
                    <span class="label">{{ __('lang.search') }}</span>
                </div>
                <a href="{{ route('home') }}" class="logo">
                    @if(LaravelLocalization::getCurrentLocale() == 'en')
                        <span class="name">Es2al</span>
                        <span class="com">.com</span>
                    @else
                        <span class="name">إسأل</span>
                        <span class="com">.كوم</span>
                    @endif
                </a>
                <div class="nav-btn mobile toggle-navbar">
                    <i data-feather="menu"></i>
                    <span class="label">{{ __('lang.menu') }}</span>
                </div>
            </div>
            <div class="search-wrapper">
                <div class="search">
                    <div class="s-icon">
                        <i data-feather="search"></i>
                    </div>
                    <input type="text" name="keywords" placeholder="{{ __('lang.search') }} ...">
                    <div class="close-search toggle-search mobile">
                        <i data-feather="x"></i>
                    </div>
                    <div class="result"></div>
                </div>
            </div>
            <div class="spacer"></div>
            <div class="navbar-nav">
                <a class="nav-btn large" href="{{ route('categories') }}">{{ __('lang.categories') }}</a>
                <a class="nav-btn large" href="{{ route('tags') }}">{{ __('lang.tags') }}</a>
                @if(Auth::user())
                    <div class="dropdown">
                        <div class="nav-btn dropdown-btn">
                            @if(Helper::notifications_count())
                                <span class="count">{{ Helper::notifications_count() }}</span>
                            @endif
                            <i data-feather="bell"></i>
                            <span class="label mobile">{{ __('lang.notifications') }}</span>
                        </div>
                        <div class="dropdown-menu notifications">
                            @forelse(Helper::notifications() as $notification)
                                <div class="dropdown-item @if(!$notification->read) not-read @endif">
                                    <img class="user-pic" src="{{ $notification->nuser->picurl }}" alt="">
                                    <div class="info">
                                        <a href="{{ $notification->url }}" notid="{{ $notification->id }}">
                                            @if($notification->type == 'answer')
                                                {{ sprintf(__('lang.notifications_answer'), $notification->nuser->fullname, $notification->title) }}
                                            @elseif($notification->type == 'best')
                                                {{ sprintf(__('lang.notifications_best'), $notification->nuser->fullname, $notification->title) }}
                                            @elseif($notification->type == 'comment')
                                                {{ sprintf(__('lang.notifications_comment'), $notification->nuser->fullname, $notification->title) }}
                                            @endif
                                        </a>
                                        <p style="color: #0006; font-size: 12px">{{ $notification->created_at->diffForHumans() }}</p>
                                    </div>
                                    @if(!$notification->read)
                                        <div class="status" notid="{{ $notification->id }}" data-tippy-content="{{ __('lang.notifications_mark_as_read') }}"></div>
                                    @endif
                                </div>
                            @empty
                                لا يوجد إشعارات
                            @endforelse
                        </div>
                    </div>
                @endif
                <div class="dropdown">
                    <div class="dropdown-btn nav-btn dropdown-btn">
                        <span class="badge">{{ LaravelLocalization::getCurrentLocale() }}</span>
                        <i data-feather="globe"></i>
                        <span class="label mobile">{{ __('lang.language') }}</span>
                    </div>
                    <div class="dropdown-menu">
                        <a href="{{ LaravelLocalization::getLocalizedURL('ar', null, [], true) }}"
                           class="dropdown-item @if(LaravelLocalization::getCurrentLocale() == 'ar') active @endif">
                            <span>العربية</span>
                        </a>
                        <a href="{{ LaravelLocalization::getLocalizedURL('en', null, [], true) }}"
                           class="dropdown-item @if(LaravelLocalization::getCurrentLocale() == 'en') active @endif">
                            <span>English</span>
                        </a>
                    </div>
                </div>
                @if(Auth::user())
                    <a class="nav-btn mobile" href="{{ route('profile', Auth::user()->id) }}">
                        <i data-feather="user"></i>
                        <span class="label mobile">{{ __('lang.profile') }}</span>
                    </a>
                    <a class="nav-btn mobile" href="{{ route('settings.general') }}">
                        <i data-feather="settings"></i>
                        <span class="label mobile">{{ __('lang.settings') }}</span>
                    </a>
                    <a class="nav-btn mobile" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i data-feather="power"></i>
                        <span class="label mobile">{{ __('lang.logout') }}</span>
                    </a>
                @else
                    <a class="nav-btn mobile" href="{{ route('tags') }}">
                        <i data-feather="tag"></i>
                        <span class="label mobile">{{ __('lang.tags') }}</span>
                    </a>
                    <a class="nav-btn mobile" href="{{ route('categories') }}">
                        <i data-feather="folder"></i>
                        <span class="label mobile">{{ __('lang.categories') }}</span>
                    </a>
                    <a class="nav-btn mobile" href="{{ route('register') }}">
                        <i data-feather="user"></i>
                        <span class="label mobile">{{ __('lang.register') }}</span>
                    </a>
                    <a class="nav-btn mobile" href="{{ route('login') }}">
                        <i data-feather="power"></i>
                        <span class="label mobile">{{ __('lang.login') }}</span>
                    </a>
                @endif
                <div class="dropdown large">
                    <div class="nav-btn dropdown-btn">
                        <i data-feather="user"></i>
                        @if(Auth::user())
                            <span class="label">{{ Auth::user()->fullname }}</span>
                        @endif
                        <i data-feather="chevron-down"></i>
                    </div>
                    <div class="dropdown-menu">
                        @if(Auth::user())
                            <a class="dropdown-item" href="{{ route('profile', Auth::user()->id) }}"><i data-feather="user"></i><span>{{ __('lang.profile') }}</span></a>
                            <a class="dropdown-item" href="{{ route('settings.general') }}"><i data-feather="settings"></i><span>{{ __('lang.settings') }}</span></a>
                            <div class="dropdown-devider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i data-feather="power"></i><span>{{ __('lang.logout') }}</span></a>
                        @else
                            <a class="dropdown-item" href="{{ route('login') }}"><i data-feather="log-in"></i><span>{{ __('lang.login') }}</span></a>
                            <a class="dropdown-item" href="{{ route('register') }}"><i data-feather="user"></i><span>{{ __('lang.register') }}</span></a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/user/components/sidebar.blade.php
<div class="sidebar p-10-m">
    @if(Route::is('question.show') && $related->count() > 0)
    <div class="widget" id="related-questions">
        <div class="widget-header">
            <span class="widget-title">
                <i data-feather="users"></i>
                <h2>{{ __('lang.related_questions') }}</h2>
            </span>
        </div>
        <div class="widget-body">
            @forelse($related as $question)
                <div class="item">
                    <a href="{{ $question->url }}">{{ $question->title }}</a>
                    <span><i data-feather="eye"></i>{{ $question->views }} {{ $question->views == 1 || $question->views == 2 || $question->views > 10 ? __('lang.view') : __('lang.views') }}</span>
                </div>
            @empty
                <p style="padding: 15px;">{{ __('lang.no_data') }}</p>
            @endforelse
        </div>
    </div>
    @endif
    <div class="widget" id="top-users">
        <div class="widget-header">
            <span class="widget-title">
                <i data-feather="users"></i>
                <h2>{{ __('lang.top_users') }}</h2>
            </span>
        </div>
        <div class="widget-body">
            <div class="tabs-header">
                <div class="tab-btn active" data="week" default="">{{ __('lang.week') }}</div>
                <div class="tab-btn" data="month">{{ __('lang.month') }}</div>
                <div class="tab-btn" data="year">{{ __('lang.year') }}</div>
                <div class="tab-btn" data="all">{{ __('lang.all_time') }}</div>
            </div>
            <div class="tab-container"></div>
        </div>
    </div>
    <div class="widget" id="hot-questions">
        <div class="widget-header">
            <span class="widget-title">
                <i data-feather="trending-up"></i>
                <h2>{{ __('lang.hot_questions') }}</h2>
            </span>
        </div>
        <div class="widget-body">
            @forelse(Stats::hot_questions() as $question)
                <div class="item">
                    <a href="{{ $question->url }}">{{ $question->title }}</a>
                    <span><i data-feather="eye"></i>{{ $question->views }} {{ $question->views == 1 || $question->views == 2 || $question->views > 10 ? __('lang.view') : __('lang.views') }}</span>
                </div>
            @empty
                <p style="padding: 15px;">{{ __('lang.no_data') }}</p>
            @endforelse
        </div>
    </div>
    <div class="widget" id="categories">
        <div class="widget-header">
            <span class="widget-title">
                <i data-feather="folder"></i>
                <h2>{{ __('lang.categories') }}</h2>
            </span>
        </div>
        <div class="widget-body">
            @forelse(Helper::categories() as $category)
                <div class="item">
                    <div class="info">
                        <a href="{{ route('questions.category', $category->slug) }}">{{ $category->name }}</a>
                        <span>{{ $category->questions->count() }} {{ __('lang.questions') }}</span>
                    </div>
                    <div class="spacer"></div>
                    <div class="cat-icon" style="background: {{ $category->color }}">
                        <img src="{{ $category->image }}">
                    </div>
                </div>
            @empty
                <p style="padding: 15px;">{{ __('lang.no_data') }}</p>
            @endforelse
        </div>
    </div>
    <div class="widget" id="tags">
        <div class="widget-header">
            <span class="widget-title">
                <i data-feather="folder"></i>
                <h2>{{ __('lang.tags') }}</h2>
            </span>
        </div>
        <div class="widget-body">
            @forelse(Helper::tags() as $tag)
                <a href="{{ route('questions.tag', $tag->name) }}" class="tag">{{ $tag->name }} ({{ $tag->questions()->count() }})</a>
            @empty
                <p style="padding: 15px;">{{ __('lang.no_data') }}</p>
            @endforelse
        </div>
    </div>
</div>

<script>
    $('#top-users .tab-btn').click(function () {
        $(this).addClass('active').siblings().removeClass('active');
        var period = $(this).attr('data');
        $.get('{{ route('sidebar.topusers') }}', {
            period: period
        }, function (data) {
            $('#top-users .tab-container').html(data);
        });
    });
    $('[default]').click();
</script>

resources/views/user/components/topusers.blade.php
@forelse($users as $user)
    <div class="item">
        <img class="user-pic" src="{{ $user->picurl }}">
        <div class="info">
            <a href="{{ route('profile', $user->id) }}">{{ $user->fullname }}</a>
            <span>
                {{ $user->pointsc }} {{ $user->pointsc == 1 || $user->pointsc == 2 || $user->pointsc > 10 ? __('lang.point') : __('lang.points') }}
            </span>
        </div>
    </div>
@empty
    <p style="padding: 15px;">{{ __('lang.no_data') }}</p>
@endforelse