routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Auth\ {
    AdminLoginController,
    LoginController,
    RegisterController
};

use App\Http\Controllers\Admin\ {
    AdminsController,
    AnswersController as AdminAnswersController,
    CategoriesController as AdminCategoriesController,
    HomeController as AdminHomeController,
    QuestionsController as AdminQuestionsController,
    ReportsController as AdminReportsController,
    SettingsController as AdminSettingsController,
    UsersController as AdminUsersController,
};

use App\Http\Controllers\User\ {
    AnswersController,
    CategoriesController,
    CommentsController,
    HomeController,
    NotificationsController,
    ProfileController,
    QuestionsController,
    ReportsController,
    SettingsController,
    SidebarController,
    TagsController,
    WizardController
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Auth Routes */
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->middleware('status.check');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);

});

/* Admin Routes */
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::group(['prefix' => 'admin'], function () {

        Route::get('/login', [AdminLoginController::class, 'login'])->name('admin.login');
        Route::post('/login', [AdminLoginController::class, 'loginAdmin'])->name('admin.loginAdmin');
        Route::post('/logout', [AdminLoginController::class, 'logout'])->name('admin.logout');

        Route::get('register', [AdminHomeController::class, 'create'])->name('admin.register');
        Route::post('register', [AdminHomeController::class, 'store'])->name('admin.register.store');
        Route::get('/', [AdminHomeController::class, 'index'])->name('admin.home');
        Route::resource('/answers', AdminAnswersController::class);
        Route::resource('/admins', AdminsController::class);
        Route::resource('/users', AdminUsersController::class);
        Route::resource('/categories', AdminCategoriesController::class);
        Route::resource('/questions', AdminQuestionsController::class);
        Route::get('/search', [AdminHomeController::class, 'search'])->name('admin.search');

        Route::get('/settings', [AdminSettingsController::class, 'index'])->name('admin.settings');
        Route::put('/settings/update', [AdminSettingsController::class, 'update'])->name('admin.settings.update');

        Route::get('/reports', [AdminReportsController::class, 'index'])->name('reports.index');
        Route::get('/reports/{id}', [AdminReportsController::class, 'show'])->name('reports.show');
        Route::get('/reports/{id}/edit', [AdminReportsController::class, 'edit'])->name('reports.edit');
        Route::get('/reports/{id}/delete/{user?}', [AdminReportsController::class, 'delete'])->name('reports.delete');
        Route::delete('/reports/{id}/deleteReport', [AdminReportsController::class, 'deleteReport'])
            ->name('reports.deleteReport');

    });
});

/* User Routes */
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {

    Route::get('/', [HomeController::class, 'index'])->name('home');

    /* Question */
    Route::get('/questions/show/{id}/{title?}', [QuestionsController::class, 'show'])->name('question.show');
    Route::get('/ask', [QuestionsController::class, 'create'])->name('user.questions.create');
    Route::post('/questions/store', [QuestionsController::class, 'store'])->name('user.questions.store');
    Route::get('/questions/{id}/edit', [QuestionsController::class, 'edit'])->name('user.questions.edit');
    Route::put('/questions/{id}/update', [QuestionsController::class, 'update'])->name('user.questions.update');
    Route::delete('/questions/{id}', [QuestionsController::class, 'destroy'])->name('user.questions.destroy');

    /* Questions */
    Route::get('/questions', [QuestionsController::class, 'latest'])->name('questions');

    /* All Newest */
    Route::get('/questions/newest', [HomeController::class, 'newest'])->name('questions.newest');
    Route::get('/questions/newest/data', [HomeController::class, 'newestData'])->name('questions.newest.data');

    /* By Interests */
    Route::get('/questions/interested', [HomeController::class, 'interested'])->name('questions.interested');
    Route::get('/questions/interested/data', [HomeController::class, 'interestedData'])
        ->name('questions.interested.data');

    /* Category */
    Route::get('/categories', [CategoriesController::class, 'index'])->name('categories');
    Route::get('/questions/{slug}', [CategoriesController::class, 'questions'])->name('questions.category');
    Route::get('/questions/category/data', [CategoriesController::class, 'questionsData'])
        ->name('questions.category.data');

    /* Tags */
    Route::get('/tags', [TagsController::class, 'index'])->name('tags');
    Route::get('/tags/{name}', [TagsController::class, 'questions'])->name('questions.tag');
    Route::get('/tags/category/data', [TagsController::class, 'questionsData'])->name('questions.tag.data');

    /* Answers */
    Route::post('/answers/store', [AnswersController::class, 'store'])->name('answers.store');
    Route::post('/answers/best', [AnswersController::class, 'best'])->name('answers.best');
    Route::post('/makeVote', [AnswersController::class, 'makeVote'])->name('makeVote');
    Route::post('/loadVotes', [AnswersController::class, 'loadVotes'])->name('loadVotes');
    Route::put('/answers/{id}/update', [AnswersController::class, 'update'])->name('user.answers.update');
    Route::delete('/answers/{id}', [AnswersController::class, 'destroy'])->name('user.answers.destroy');

    /* Comments */
    Route::post('/comments/store', [CommentsController::class, 'store'])->name('user.comments.store');
    Route::put('/comments/{id}/update', [CommentsController::class, 'update'])->name('user.comments.update');
    Route::delete('/comments/{id}', [CommentsController::class, 'destroy'])->name('user.comments.destroy');

    /* Settings */
    Route::get('/settings', [SettingsController::class, 'general'])->name('settings.general');
    Route::put('/settings/general/update', [SettingsController::class, 'update_general'])
        ->name('settings.general.update');
    Route::get('/settings/changepass', [SettingsController::class, 'changepass'])->name('settings.changepass');
    Route::put('/settings/changepass/update', [SettingsController::class, 'update_password'])
        ->name('settings.password.update');
    Route::get('/settings/profile', [SettingsController::class, 'profile'])->name('settings.profile');
    Route::put('/settings/profile/update', [SettingsController::class, 'update_profile'])
        ->name('settings.profile.update');
    Route::get('/settings/myquestions', [SettingsController::class, 'myquestions'])->name('settings.myquestions');

    /* Wizard */
    Route::get('/wizard/step1', [WizardController::class, 'step1'])->name('wizard.step1');
    Route::get('/wizard/step2', [WizardController::class, 'step2'])->name('wizard.step2');
    Route::get('/wizard/step3', [WizardController::class, 'step3'])->name('wizard.step3');
    Route::post('/wizard/step1/store', [WizardController::class, 'step1_store'])->name('wizard.step1.store');
    Route::post('/wizard/step2/store', [WizardController::class, 'step2_store'])->name('wizard.step2.store');
    Route::post('/wizard/step3/store', [WizardController::class, 'step3_store'])->name('wizard.step3.store');


    /* Profile */
    Route::get('/profile/{user_id}', [ProfileController::class, 'index'])->name('profile');
    Route::post('/profile/uploadPicture', [ProfileController::class, 'uploadPicture'])->name('profile.picture');
    Route::post('/profile/uploadCover', [ProfileController::class, 'uploadCover'])->name('profile.cover');

    /* Notifications */
    Route::get('/notifications/get', [NotificationsController::class, 'get'])->name('notifications.get');
    Route::post('/notifications/read', [NotificationsController::class, 'read'])->name('notifications.read');

    /* Sidebar */
    Route::get('/sidebar/topusers', [SidebarController::class, 'topUsers'])->name('sidebar.topusers');

    /* Search */
    Route::get('/search', [HomeController::class, 'search'])->name('user.search');

    /* Report */
    Route::post('/report/question', [ReportsController::class, 'reportQuestion'])->name('report.question');

    Route::get('/splash', [HomeController::class, 'splash'])->name('home.splash');

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $fillable = [
        'name', 'slug', 'description'
    ];

    public function questions()
    {
        return $this->hasMany('App\Models\Question');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    public function show($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.show', compact('category'));
    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(Request $request)
    {

        $rules = [
            'name' => 'required',
            'slug' => 'required',
            'color' => 'required',
            'image' => 'required'
        ];

        $attributes = [
            'name' => __('admin.name'),
            'slug' => __('admin.slug'),
            'color' => __('admin.color'),
            'image' => __('admin.image')
        ];

        $this->validate($request, $rules, [], $attributes);

        $user = new Category();
        $user->name = $request->name;
        $user->slug = $request->slug;
        $user->description = $request->description;
        $user->color = $request->color;
        $user->image = $request->image;
        $user->save();

        if ($request->has('create_another')) {
            return redirect()->route('categories.create')->with('success', __('lang.success'));
        }

        return redirect()->route('categories.index')->with('success', __('lang.success'));
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('admin.categories.edit', compact('category'));
    }

    public function update(Request $request, $id)
    {

        $rules = [
            'name' => 'required',
            'slug' => 'required',
            'color' => 'required',
            'image' => 'required'
        ];

        $attributes = [
            'name' => __('admin.name'),
            'slug' => __('admin.slug'),
            'color' => __('admin.color'),
            'image' => __('admin.image')
        ];

        $this->validate($request, $rules, [], $attributes);

        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->slug = $request->slug;
        $category->description = $request->description;
        $category->save();

        return redirect()->route('categories.index')->with('success', __('lang.success'));
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return redirect()->route('categories.index')->with('success', __('lang.success'));
    }
}

app/Http/Controllers/User/CategoriesController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Answer;
use App\Models\Category;
use App\Helpers\Settings;
use App\Http\Controllers\Controller;
use App\Notification;
use App\Models\Question;
use App\Models\Vote;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoriesController extends Controller
{

    public function index()
    {
        $categories = Category::all();
        
        return view('user.categories.index', compact('categories'));
    }

    public function questions($slug)
    {
        $category = Category::where('slug', $slug)->get()->shift();
        $last = Question::where('category_id', $category->id)->paginate(Settings::get('perpage'))->lastPage();
        $route = 'questions.category.data';

        return view('user.categories.questions', compact('category', 'last', 'route'));
    }

    public function questionsData(Request $request)
    {
        $category = Category::where('slug', $request->slug)->get()->shift();
        $questions = Question::where('category_id', $category->id)->paginate(Settings::get('perpage'));

        return view('user.questionslist', compact('questions'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin/layouts.app')

@section('title', __('admin.create_category'))

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ @asset('colorpicker/css/colorpicker.css') }}" />
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ @asset('colorpicker/js/colorpicker.js') }}"></script>
@endpush

@push('js')
    <script>

        $('.color').ColorPicker({
            onSubmit: function(hsb, hex, rgb, el) {
                $(el).val('#' + hex);
                $(el).ColorPickerHide();
            },
            onBeforeShow: function () {
                $(this).ColorPickerSetColor(this.value);
            }
        }).bind('keyup', function(){
            $(this).ColorPickerSetColor(this.value);
        });

    </script>
@endpush

@section('content')
    <div class="toolbar">
        <div class="title">{{ __('admin.create_category') }}</div>
    </div>
    <div class="panel">
        <form action="{{ route('categories.store') }}" method="post">
            {{ csrf_field() }}
            <div class="body">
                <div class="field {{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.name') }}</label>
                    <div class="control">
                        <input name="name" type="text" value="{{ old('name') }}" data-validation="required">
                        @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.slug') }}</label>
                    <div class="control">
                        <input name="slug" type="text" value="{{ old('slug') }}">
                        @if ($errors->has('slug'))
                            <span class="help-block">{{ $errors->first('slug') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('description') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.description') }}</label>
                    <div class="control">
                        <textarea name="description" rows="5">{{ old('description') }}</textarea>
                        @if ($errors->has('description'))
                            <span class="help-block">{{ $errors->first('description') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('color') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.color') }}</label>
                    <div class="control">
                        <input name="color" class="color" type="text" value="{{ old('color') }}">
                        @if ($errors->has('color'))
                            <span class="help-block">{{ $errors->first('color') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('image') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.image') }}</label>
                    <div class="control">
                        <input name="image" type="text" value="{{ old('image') }}">
                        @if ($errors->has('image'))
                            <span class="help-block">{{ $errors->first('image') }}</span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="footer">
                <button type="submit" name="create_another" class="btn btn-primary">{{ __('admin.create_and_add_another') }}</button>
                <button type="submit" name="create" class="btn btn-primary">{{ __('admin.create') }}</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin/layouts.app')

@section('title', __('admin.edit_category') . ': ' . $category->name)

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ @asset('colorpicker/css/colorpicker.css') }}" />
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ @asset('colorpicker/js/colorpicker.js') }}"></script>
@endpush

@push('js')
    <script>

        $('.color').ColorPicker({
            onSubmit: function(hsb, hex, rgb, el) {
                $(el).val('#' + hex);
                $(el).ColorPickerHide();
            },
            onBeforeShow: function () {
                $(this).ColorPickerSetColor(this.value);
            }
        }).bind('keyup', function(){
            $(this).ColorPickerSetColor(this.value);
        });

    </script>
@endpush

@section('content')
    <div class="toolbar">
        <div class="title">{{ __('admin.edit_category') }}</div>
    </div>
    <div class="panel">
        <form action="{{ route('categories.update', $category->id) }}" method="post">
            <input type="hidden" name="_method" value="PUT">
            {{ csrf_field() }}
            <div class="body">
                <div class="field {{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.name') }}</label>
                    <div class="control">
                        <input name="name" type="text" value="{{ old('name', $category->name) }}">
                        @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.slug') }}</label>
                    <div class="control">
                        <input name="slug" type="text" value="{{ old('slug', $category->slug) }}">
                        @if ($errors->has('slug'))
                            <span class="help-block">{{ $errors->first('slug') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('description') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.description') }}</label>
                    <div class="control">
                        <textarea name="description" rows="5">{{ old('description', $category->description) }}</textarea>
                        @if ($errors->has('description'))
                            <span class="help-block">{{ $errors->first('description') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('color') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.color') }}</label>
                    <div class="control">
                        <input name="color" type="text" class="color" value="{{ old('color', $category->color) }}">
                        @if ($errors->has('color'))
                            <span class="help-block">{{ $errors->first('color') }}</span>
                        @endif
                    </div>
                </div>
                <div class="field {{ $errors->has('image') ? ' has-error' : '' }}">
                    <label class="field-label">{{ __('admin.image') }}</label>
                    <div class="control">
                        <input name="image" type="text" value="{{ old('image', $category->image) }}">
                        @if ($errors->has('image'))
                            <span class="help-block">{{ $errors->first('image') }}</span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="footer">
                <button type="submit" name="submit" class="btn btn-primary">{{ __('admin.save') }}</button>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin/layouts.app')

@section('title', __('admin.categories'))

@section('content')
    <div class="toolbar">
        <div class="title">{{ __('admin.categories') }}</div>
        <div class="search">
            <i data-feather="search"></i>
            <input type="text" id="tableSearch" placeholder="{{ __('admin.search') }}">
        </div>
        <div class="fill"></div>
        <a class="btn btn-primary" href="{{ route('categories.create') }}">{{ __('admin.create_category') }}</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>{{ __('admin.id') }}</th>
                <th>{{ __('admin.icon') }}</th>
                <th>{{ __('admin.name') }}</th>
                <th>{{ __('admin.slug') }}</th>
                <th>{{ __('admin.questions') }}</th>
                <th>{{ __('admin.control') }}</th>
            </tr>
        </thead>
        <tbody>
        @forelse($categories as $category)
            <tr>
                <td class="center">{{ $category->id }}</td>
                <td><div class="cat-icon" style="background-color: {{ $category->color }}"><img src="{{ $category->image }}"></div></td>
                <td>{{ $category->name }}</td>
                <td>{{ $category->slug }}</td>
                <td>{{ $category->questions->count() }}</td>
                <td>
                    <a data-tippy-content="{{ __('admin.view') }}" class="action-btn" href="{{ route('categories.show', $category->id) }}"><i data-feather="eye"></i></a>
                    <a data-tippy-content="{{ __('admin.edit') }}" class="action-btn" href="{{ route('categories.edit', $category->id) }}"><i data-feather="edit"></i></a>
                    <form action="{{ route('categories.destroy', $category->id) }}" method="POST"
                          style="display: inline"
                          onsubmit="return confirm('{{ __('admin.are_you_sure') }}');">
                        <input type="hidden" name="_method" value="DELETE">
                        {{ csrf_field() }}
                        <button data-tippy-content="{{ __('admin.delete') }}" class="action-btn"><i data-feather="trash-2"></i></button>
                    </form>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="100%" style="text-align: center; padding: 20px">{{ __('admin.no_data') }}</td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin/layouts.app')

@section('title', __('admin.category_details') . ': ' . $category->name)

@section('content')
    <div class="toolbar">
        <div class="ptitle">{{ __('admin.category_details') }}</div>
        <div class="fill"></div>
        <form action="{{ route('categories.destroy', $category->id) }}" method="POST"
              style="display: inline"
              onsubmit="return confirm('{{ __('admin.are_you_sure') }}');">
            <input type="hidden" name="_method" value="DELETE">
            {{ csrf_field() }}
            <button data-tippy-content="{{ __('admin.delete') }}" class="btn btn-secondary icon"><i data-feather="trash-2"></i></button>
        </form>
        <a data-tippy-content="{{ __('admin.edit') }}" class="btn btn-primary icon" href="{{ route('categories.edit', $category->id) }}"><i data-feather="edit"></i></a>
    </div>
    <div class="panel">
        <div class="info">
            <label>{{ __('admin.id') }}</label>
            <div>{{ $category->id }}</div>
        </div>
        <div class="info">
            <label>{{ __('admin.name') }}</label>
            <div>{{ $category->name }}</div>
        </div>
        <div class="info">
            <label>{{ __('admin.slug') }}</label>
            <div>{{ $category->slug }}</div>
        </div>
        <div class="info">
            <label>{{ __('admin.questions') }}</label>
            <div>{{ $category->questions->count() }}</div>
        </div>
        <div class="info">
            <label>{{ __('admin.icon') }}</label>
            <div>
                <div class="cat-icon" style="background-color: {{ $category->color }}"><img src="{{ $category->image }}"></div>
            </div>
        </div>
        <div class="info">
            <label>{{ __('admin.created_at') }}</label>
            <div>{{ $category->created_at }}</div>
        </div>
    </div>
    <div class="toolbar">
        <div class="title">{{ __('admin.category_questions') }}</div>
        <div class="search">
            <i data-feather="search"></i>
            <input type="text" id="tableSearch" placeholder="{{ __('admin.search') }}">
        </div>
    </div>
    <table>
        <thead>
        <tr>
            <th>{{ __('admin.id') }}</th>
            <th>{{ __('admin.solved') }}</th>
            <th>{{ __('admin.title') }}</th>
            <th>{{ __('admin.author') }}</th>
            <th>{{ __('admin.answers') }}</th>
            <th>{{ __('admin.control') }}</th>
        </tr>
        </thead>
        <tbody>
        @forelse($category->questions as $question)
            <tr>
                <td class="center">{{ $question->id }}</td>
                <td class="center">
                    @if($question->hasBestAnswer())
                        <div class="status solved"><i data-feather="check-circle"></i>{{ __('admin.solved') }}</div>
                    @else
                        <div class="status unsolved"><i data-feather="help-circle"></i>{{ __('admin.unsolved') }}</div>
                    @endif
                </td>
                <td><span data-tippy-content="{{ $question->title }}">{{ mb_substr($question->title, 0, 40) }} ...</span></td>
                <td><a href="{{ route('users.show', $question->user->id) }}">{{ $question->user->fullname }}</a></td>
                <td>{{ $question->answers->count() }}</td>
                <td>
                    <a data-tippy-content="{{ __('admin.view') }}" class="action-btn" href="{{ route('questions.show', $question->id) }}"><i data-feather="eye"></i></a>
                    <a data-tippy-content="{{ __('admin.edit') }}" class="action-btn" href="{{ route('questions.edit', $question->id) }}"><i data-feather="edit"></i></a>
                    <form action="{{ route('questions.destroy', $question->id) }}" method="POST"
                          style="display: inline"
                          onsubmit="return confirm('{{ __('admin.are_you_sure') }}');">
                        <input type="hidden" name="_method" value="DELETE">
                        {{ csrf_field() }}
                        <button data-tippy-content="{{ __('admin.delete') }}" class="action-btn"><i data-feather="trash-2"></i></button>
                    </form>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="100%" style="text-align: center">NO DATA</td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection